### ISSUE TITLE
A question related to this module

### ISSUE THREAD

**Issue by CWhedgehog** [AnthonyChenevier/EnhancedGrowthVatLearning#7] opened 2024-11-09 09:34 UTC
How did it happen: One of my children in the cultivation warehouse became a child during their growth stage, and this error popped up.The report states that it is related to the MOD TD-Enhancement-Pack

Exception ticking GrowthVat363505 (at (165, 0, 201)). Suppressing further errors. Exception: System.NullReferenceException: Object reference not set to an instance of an object.
[Ref 2B40F0AA]
 at RimWorld.LearningUtility.LearningRateFactor (Verse.Pawn pawn) [0x00015] in <2a40c3593b334f29ac3cb3d32d652351>:0 
 at GrowthVatsOverclocked.VatExtensions.HediffComp_OverclockedVatLearning.LearnMode (RimWorld.Pawn_SkillTracker skillTracker, GrowthVatsOverclocked.Data.LearningMode mode) [0x00052] in <6fbb1fdc98364812ab5af83f3f1ceac2>:0 
 at GrowthVatsOverclocked.VatExtensions.HediffComp_OverclockedVatLearning.Learn () [0x00058] in <6fbb1fdc98364812ab5af83f3f1ceac2>:0 
 at GrowthVatsOverclocked.ClassExtensions.Hediff_VatLearning_HarmonyPatch.Learn_Prefix (Verse.Hediff_VatLearning __instance) [0x00017] in <6fbb1fdc98364812ab5af83f3f1ceac2>:0 
 at Verse.Hediff_VatLearning.Learn () [0x0000e] in <2a40c3593b334f29ac3cb3d32d652351>:0 
     - PREFIX makeitso.growthvatsoverclocked: Boolean GrowthVatsOverclocked.ClassExtensions.Hediff_VatLearning_HarmonyPatch:Learn_Prefix(Hediff_VatLearning __instance)
 at Verse.Hediff_VatLearning.PostTick () [0x00019] in <2a40c3593b334f29ac3cb3d32d652351>:0 
 at RimWorld.Building_GrowthVat.Tick () [0x001d0] in <2a40c3593b334f29ac3cb3d32d652351>:0 
 at Verse.TickList.Tick () [0x0017d] in <2a40c3593b334f29ac3cb3d32d652351>:0 
     - TRANSPILER net.pardeike.rimworld.lib.harmony: IEnumerable`1 VisualExceptions.ExceptionsAndActivatorHandler:Transpiler(IEnumerable`1 instructions, MethodBase original)
     - POSTFIX Uuugggg.rimworld.TD_Enhancement_Pack.main: Void TD_Enhancement_Pack.TickGrow_PlantHarvest:Postfix(TickerType ___tickType)
     - POSTFIX Uuugggg.rimworld.TD_Enhancement_Pack.main: Void TD_Enhancement_Pack.TickGrow:Postfix(TickerType ___tickType)
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Log.Error_Patch7 (string)
Verse.Log:ErrorOnce (string,int)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.TickList.Tick_Patch2 (Verse.TickList)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.TickManager.DoSingleTick_Patch4 (Verse.TickManager)
Verse.TickManager:TickManagerUpdate ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Game.UpdatePlay_Patch2 (Verse.Game)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Root_Play.Update_Patch1 (Verse.Root_Play)

**Comment by CWhedgehog** [comment] 2024-11-09 09:35
It seems that it's not 100% triggered, only one of the three children experienced this problem

**Comment by AnthonyChenevier** [comment] 2024-11-10 10:08
I haven't seen this particular mod before, so I can't be sure what the cause is right away. I'll try and do some testing and get back to you with the results. 

Just to confirm - you went from baby to child and the error popped up?

EDIT: did a quick test on this one and nothing unusual came up. Will keep an eye on it though. Let me know if you can find a way to replicate it.

Thanks for the report!

**Comment by CWhedgehog** [comment] 2024-11-11 08:51
I still have this problem, it may be caused by other mods, I guess it could be performance fish? After this problem occurred, my game became very slow, but as long as I put the child back into the training room, it will solve this problem.

A new discovery is that errors will be thrown when the overclocked vat learning value is 100%. Yes, it will be fixed at 100% instead of increasing skill experience and resetting to zero. As long as I put the child back into the training room, the problem will be solved (it only occurs when I change from a baby to a child at the age of 3)

**Comment by AnthonyChenevier** [comment] 2024-11-12 00:40
I think this may be caused by TD enhancement pack using a harmony transpiler patch, which is breaking my mod's functionality *sometimes*.  As I can't replicate the bug with that mod installed I'm not sure how to fix it yet, but will keep an eye out for further occurences.

**Comment by CWhedgehog** [comment] 2024-11-12 03:02
Okay, thank you for your reply ♡

**Comment by AnthonyChenevier** [comment] 2024-11-18 12:06
@CWhedgehog Another user had a similar issue - check my closed issues for a workaround that may work for you as well if you are still getting the errors. I'm going to close this now

**Closed as completed by AnthonyChenevier** 2024-11-18 12:06 UTC
Labels: mod incompatibility

**Comment by CWhedgehog** [comment] 2024-11-18 14:40
Yes, this workaround can solve the problem
